#declare a global source file list
set_property(GLOBAL PROPERTY source_list)
#define an "add_source" function for easy adding of available source files.
#function(add_source)
#    get_property(tmp GLOBAL PROPERTY source_list)
#    foreach(arg ${ARGV})
#        set(tmp "${tmp} ${arg}")
#    endforeach()
#    set_property(GLOBAL PROPERTY source_list "${tmp}")
#endfunction(add_source)

#macro (add_sources)
#    file (RELATIVE_PATH _relPath "${PROJECT_SOURCE_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}")
#    foreach (_src ${ARGN})
#        if (_relPath)
#            list (APPEND source_list "${_relPath}/${_src}")
#        else()
#            list (APPEND source_list "${_src}")
#        endif()
#    endforeach()
#    if (_relPath)
#        # propagate SRCS to parent directory
#        set (SRCS source_list PARENT_SCOPE)
#    endif()
#endmacro()