#!/bin/bash
### Check for dir, if not found create it using the mkdir ##
[ ! -d "./build" ] && mkdir -p "build"

#run cmake for blob_example build. BUILD_STATIC and BUILD_EXECUTABLES option flags are required for libjpeg use. Said flags are not needed if libjpeg is not used.
cd ./build
printf "\nRunning CMAKE\n\n"

command="cmake .. -DBUILD_BLOB_EXAMPLE=ON -DBUILD_STATIC=ON -DBUILD_EXECUTABLES=OFF"
eval $command

#configure libjpeg and generate the included files used. Again this is only needed for libjpeg use:
cd ../examples/helpers/libjpeg/
printf "\nConfiguring libjpeg\n\n"
#./configure CFLAGS='-O2' --disable-shared 
./configure --prefix="$PWD/build"

#build the project from the makefile generated by cmake:
printf "\nRunning MAKE in the build directory\n\n"
cd ../../../build/
make VERBOSE=1

