#!/bin/bash
#this is a bash script to automatically handle properly building this example.
#a CMAKE and a make
### Check for dir, if not found create it using the mkdir ##
[ ! -d "./build" ] && mkdir -p "build"

cd ./build
printf "\nRunning CMAKE\n\n"
#this runs cmake with 2 flags, all flags in cmake must be preceded with a "-D":
#1. BUILD_BLOB_EXAMPLE=ON: This is the option we made in our cmake file to do all the additional work if we wanted to test blob_labelling in linux (which is what this example is)
#2. CMAKE_BUILD_TYPE=Debug: This tells CMAKE to build the extra info needed to be able to run gdb or other debug programs on our executable. to build without these, set DCMAKE_BUILD_TYPE=Release or MinSizeRel or RelWithDebInfo

# we store the comand in a variable and execute it all at once using the eval command

command="cmake .. -DBUILD_BLOB_EXAMPLE=ON -DCMAKE_BUILD_TYPE=Debug"
eval $command

#build the project from the makefile generated by cmake:
printf "\nRunning MAKE in the build directory\n\n"
#cd ./build/
make VERBOSE=1

